
root: /

Home: /
Archives: /archives
About: /about

language: zh

author: baocaixiong
description:

github: https://github.com/baocaixiong
email: YmFvY2FpeGlvbmdAZ21haWwuY29t(base64)

favicon: /favicon.ico


# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-adoubi.css
